<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Laporan Manajemen Proyek</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background: white;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
            font-size: 12px;
        }
        .summary {
            display: flex;
            gap: 15px;
            margin-bottom: 30px;
            justify-content: space-between;
        }
        .summary-box {
            flex: 1;
            border: 1px solid #ddd;
            padding: 15px;
            text-align: center;
            background: #f9f9f9;
        }
        .summary-box h3 {
            margin: 0 0 10px 0;
            font-size: 12px;
            color: #666;
        }
        .summary-box .value {
            font-size: 18px;
            font-weight: bold;
            color: #333;
        }
        .section-title {
            background: #333;
            color: white;
            padding: 10px;
            margin-top: 25px;
            margin-bottom: 10px;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th {
            background: #f0f0f0;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 11px;
            font-weight: bold;
        }
        table td {
            border: 1px solid #ddd;
            padding: 8px;
            font-size: 11px;
        }
        table tr:nth-child(even) {
            background: #f9f9f9;
        }
        .project-section {
            page-break-inside: avoid;
            margin-bottom: 20px;
        }
        .project-title {
            background: #667eea;
            color: white;
            padding: 10px;
            margin-bottom: 10px;
            font-weight: bold;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 LAPORAN MANAJEMEN PROYEK</h1>
        <p>Tanggal Cetak: {{ date('d F Y H:i:s') }}</p>
    </div>

    <div class="summary">
        <div class="summary-box">
            <h3>Total Upah Tukang</h3>
            <div class="value">Rp {{ number_format($totalUpahTukang) }}</div>
        </div>
        <div class="summary-box">
            <h3>Total Upah Kenek</h3>
            <div class="value">Rp {{ number_format($totalUpahKenek) }}</div>
        </div>
        <div class="summary-box">
            <h3>Total Material</h3>
            <div class="value">Rp {{ number_format($totalMaterial) }}</div>
        </div>
        <div class="summary-box">
            <h3>Total Keseluruhan</h3>
            <div class="value">Rp {{ number_format($grandTotal) }}</div>
        </div>
    </div>

    <div class="section-title">DETAIL PER PROYEK</div>

    @foreach($projects as $project)
        <div class="project-section">
            <div class="project-title">
                {{ $project->nama_proyek }} ({{ $project->tanggal_proyek }})
            </div>

            <table>
                <tr>
                    <th>Upah Tukang</th>
                    <th>Upah Kenek</th>
                    <th>Material</th>
                    <th>Total Biaya</th>
                    <th>Jumlah Pekerja</th>
                    <th>Transaksi</th>
                </tr>
                <tr>
                    <td>Rp {{ number_format($project->transactions->where('kategori', 'Upah Tukang')->sum('jumlah')) }}</td>
                    <td>Rp {{ number_format($project->transactions->where('kategori', 'Upah Kenek')->sum('jumlah')) }}</td>
                    <td>Rp {{ number_format($project->transactions->where('kategori', 'Material')->sum('jumlah')) }}</td>
                    <td><strong>Rp {{ number_format($project->transactions->sum('jumlah')) }}</strong></td>
                    <td>{{ $project->workers->count() }}</td>
                    <td>{{ $project->transactions->count() }}</td>
                </tr>
            </table>
        </div>
    @endforeach

    <div class="footer">
        Generated by Project Management System
    </div>

</body>
</html>
